env:
  browser: true,
  es6: true
extends: "airbnb"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
rules: {
  react/jsx-one-expression-per-line: 'off',
  no-use-before-define: ["error", { "functions": false, "classes": true, "variables": true }],
  max-len: 'off',
  object-curly-newline: 'off',
}
