export const SET_HIDDEN_WORD = 'SET_HIDDEN_WORD';

export const RESTORE_LIFE = 'RESTORE_LIFE';
export const CHANGE_LIFE = 'CHANGE_LIFE';

export const SET_PRESSED_LETTER = 'SET_PRESSED_LETTER';

export const SET_FINAL_TIME = 'SET_FINAL_TIME';

export const SET_COUNT_WORDS = 'SET_COUNT_WORDS';
